<?php

namespace App\Enums;

enum KeteranganTransferDetail: string
{
    case NOMINAL_TRANSFER = 'NOMINAL TRANSFER';
    case NOMINAL_PENGELUARAN = 'NOMINAL PENGELUARAN';
    case NOMINAL_PEMASUKAN = 'NOMINAL PEMASUKAN';
    case NOMINAL_SETORAN = 'NOMINAL SETORAN';
    case NOMINAL_PENARIKAN = 'NOMINAL PENARIKAN';
    case BIAYA_ADMIN = 'BIAYA ADMIN';
    case BIAYA_TRANSFER = 'BIAYA TRANSFER';
}
