<?php

namespace App\Enums;

enum TipeTransfer: string
{
    case TRANSFER_VIA_ATM_NASABAH = 'TRANSFER VIA ATM NASABAH';
    case TRANSFER_TUNIA = 'TRANSFER TUNAI';
    case MUTASI_SALDO = 'MUTASI SALDO';
    case TARIK_TUNAI = 'TARIK TUNAI';
    case PENJUALAN_PULSA = 'PENJUALAN PULSA';
    case PENJUALAN_PAKET_DATA = 'PENJUALAN PAKET DATA';
    case PRODUKTIF = 'PRODUKTIF';
}
